version: '3.4'

services:
  appserver:
    image: ${DOCKER_REGISTRY-}teenkom-blitzjob-appserver
    build:
      context: .
      dockerfile: Caiju.TeenKom.Blitzjob.AppServer/Dockerfile
    ports:
       - 443:443
       - 80:80
  tk3:
    image: ${DOCKER_REGISTRY-}teenkom-tk3
    build:
      context: .
      dockerfile: Caiju.TeenKom.TK3/Dockerfile

